---
- name: install java and gemfire
  hosts: all
  remote_user: centos
  become: true
  gather_facts: true
  vars:
    bucket_name: gemfire-fe-artifacts
    jdk_file_name: jdk-8u144-linux-x64.rpm
    gemfire_file_name: pivotal-gemfire-9.1.0.tar.gz
  tasks:
    - include: tasks/yum-update.yml
    - include: tasks/install-jdk.yml
    - include: tasks/install-gemfire.yml

- name: provision locators
  hosts: locators
  remote_user: centos
  become: true
  gather_facts: true
  vars:
    locator_user: centos
    locator_group: centos
    locator_port: 10334
    properties_file: locator.properties
  tasks:
    - include: tasks/copy-gemfire-properties.yml
    - include: tasks/create-locator-unit.yml

- name: provision servers
  hosts: servers
  remote_user: centos
  become: true
  gather_facts: true
  vars:
    server_user: centos
    server_group: centos
    locator_port: 10334
    server_port: 40404
    properties_file: server.properties
  tasks:
    - include: tasks/copy-gemfire-properties.yml
    - include: tasks/create-server-dirs.yml
    - include: tasks/create-server-unit.yml
