---
- name: rolling OS update
  hosts: all
  remote_user: centos
  become: true
  gather_facts: true
  serial: 1
  vars:
    server_user: centos
    log_file_path: "/home/{{ server_user }}/{{ ansible_hostname }}/{{ ansible_hostname }}.log"
    search_regex: ???
  tasks:
  - include_tasks: tasks/yum-update.yml
  - include_tasks: tasks/reboot-server.yml
  - include_tasks: tasks/wait-for-server-ssh.yml
  - include_tasks: tasks/wait-for-log-entry.yml
  - name: sleep to ensure server is fully functional
    pause:
      seconds: 10