---
- name: rolling cluster update
  hosts: servers
  remote_user: centos
  become: true
  gather_facts: true
  serial: 1
  vars:
    bucket_name: gemfire-fe-artifacts
    gemfire_boot_jar: ???
    server_user: centos
  tasks:
  - name: stop gemfire server
    systemd:
      name: gemfire-server
      state: stopped
  - name: "download boot jar {{ gemfire_boot_jar }}"
    s3:
      bucket: "{{ bucket_name }}"
      object: "{{ gemfire_boot_jar }}"
      dest: "/opt/app/jars/{{ gemfire_boot_jar }}"
      mode: get
  - name: start gemfire server
    systemd:
      name: gemfire-server
      state: started
  - name: search for log file
    find:
      paths: "/home/{{ server_user }}/{{ ansible_hostname }}"
      patterns: "{{ ansible_hostname }}.log"
    register: log_files
  - name: wait for server to start
    wait_for:
      path: "{{ item.path }}"
      state: present
      search_regex: "CacheServer Configuration"
    with_items: "{{ log_files.files }}"
  - name: sleep to ensure server is fully functional
    pause:
      seconds: 10