apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http-port
    protocol: TCP
  selector:
    app: test-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: us.gcr.io/fe-tdalsing/test-app:0.0.1-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-port
        env:
        - name: locator_host
          value: "gemfire-locator-0.gemfire-locator.default.svc.cluster.local"
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
           cpu: "500m"
           memory: 1Gi
